import {
  ArrowLeftRight,
  Backpack,
  Blocks,
  Braces,
  Bug,
  Calculator,
  Clapperboard,
  Compass,
  Cookie,
  Crosshair,
  DatabaseBackup,
  Flag,
  Gamepad2,
  Keyboard,
  MonitorSmartphone,
  MousePointerClick,
  Package,
  Puzzle,
  RadioTower,
  Repeat,
  Rocket,
  Split,
  Sword,
  Tags,
  Terminal,
  Timer,
  TrafficCone,
  Trophy,
  Wrench,
  Zap,
  BellRing,
  BookA,
  CaseSensitive,
  Copy,
  Factory,
  Hourglass,
  LifeBuoy,
  Mouse,
  Navigation,
  PersonStanding,
  ShoppingCart,
  StickyNote,
  Hammer,
  Server,
  Users,
  type LucideIcon,
} from "lucide-react";

/** One icon per lesson, drawn in the same line style (no emoji fonts). */
export const LESSON_ICONS: Record<string, LucideIcon> = {
  "studio-tour": Compass,
  "first-script": Terminal,
  "script-types": MonitorSmartphone,
  variables: Package,
  "math-strings": Calculator,
  "if-statements": Split,
  loops: Repeat,
  functions: Puzzle,
  tables: Backpack,
  parts: Blocks,
  events: Zap,
  leaderstats: Trophy,
  gui: MousePointerClick,
  tweens: Clapperboard,
  prompts: Keyboard,
  "remote-events": RadioTower,
  datastores: DatabaseBackup,
  modules: Wrench,
  "project-obby": Flag,
  debugging: Bug,
  "collection-service": Tags,
  runservice: Timer,
  raycasting: Crosshair,
  oop: Cookie,
  tools: Sword,
  "round-system": TrafficCone,
  dictionaries: BookA,
  "string-tools": CaseSensitive,
  instances: Copy,
  "task-library": Hourglass,
  attributes: StickyNote,
  characters: PersonStanding,
  "user-input": Mouse,
  "remote-functions": ArrowLeftRight,
  bindables: BellRing,
  "project-shop": ShoppingCart,
  "project-tycoon": Factory,
  pcall: LifeBuoy,
  cframes: Navigation,
};

/** One icon per unit (chapter), in chapter order. */
export const UNIT_ICONS: LucideIcon[] = [
  Rocket,
  Braces,
  Zap,
  RadioTower,
  Gamepad2,
  Crosshair,
  Hammer,
  Users,
  Server,
];
