/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as UNameRouteImport } from './routes/u/$name'
import { Route as ForumNewRouteImport } from './routes/forum/new'
import { Route as ForumIdRouteImport } from './routes/forum/$id'
import { Route as ApiImgIdKindRouteImport } from './routes/api/img.$id.$kind'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const UNameRoute = UNameRouteImport.update({
  id: '/u/$name',
  path: '/u/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNewRoute = ForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgIdKindRoute = ApiImgIdKindRouteImport.update({
  id: '/api/img/$id/$kind',
  path: '/api/img/$id/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/errors': typeof ErrorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/u/$name': typeof UNameRoute
  '/forum/': typeof ForumIndexRoute
  '/api/img/$id/$kind': typeof ApiImgIdKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/errors': typeof ErrorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/u/$name': typeof UNameRoute
  '/forum': typeof ForumIndexRoute
  '/api/img/$id/$kind': typeof ApiImgIdKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/errors': typeof ErrorsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/u/$name': typeof UNameRoute
  '/forum/': typeof ForumIndexRoute
  '/api/img/$id/$kind': typeof ApiImgIdKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/errors'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/playground'
    | '/profile'
    | '/forum/$id'
    | '/forum/new'
    | '/u/$name'
    | '/forum/'
    | '/api/img/$id/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/errors'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/playground'
    | '/profile'
    | '/forum/$id'
    | '/forum/new'
    | '/u/$name'
    | '/forum'
    | '/api/img/$id/$kind'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/errors'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/playground'
    | '/profile'
    | '/forum/$id'
    | '/forum/new'
    | '/u/$name'
    | '/forum/'
    | '/api/img/$id/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  ErrorsRoute: typeof ErrorsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ForumIdRoute: typeof ForumIdRoute
  ForumNewRoute: typeof ForumNewRoute
  UNameRoute: typeof UNameRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ApiImgIdKindRoute: typeof ApiImgIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$name': {
      id: '/u/$name'
      path: '/u/$name'
      fullPath: '/u/$name'
      preLoaderRoute: typeof UNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/new': {
      id: '/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof ForumNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img/$id/$kind': {
      id: '/api/img/$id/$kind'
      path: '/api/img/$id/$kind'
      fullPath: '/api/img/$id/$kind'
      preLoaderRoute: typeof ApiImgIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  ErrorsRoute: ErrorsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ForumIdRoute: ForumIdRoute,
  ForumNewRoute: ForumNewRoute,
  UNameRoute: UNameRoute,
  ForumIndexRoute: ForumIndexRoute,
  ApiImgIdKindRoute: ApiImgIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
